Feature/#5
Lv-581-Python-project/todoProject pull request #12
Opened 2021-03-10 13:43 UTC by SLDem

2021-03-10 13:47 UTC, StepanTchynetskyi requested changes

2021-03-10 13:47 UTC, StepanTchynetskyi commented on user/views.py
> +from lists.models import ToDoList
from list_project.models import List

2021-03-10 13:47 UTC, StepanTchynetskyi commented on user/views.py
> +        lists = ToDoList.objects.filter(user_id=user.pk)
ToDoList change to List

2021-03-10 19:41 UTC, StepanTchynetskyi approved these changes

2021-03-11 09:44 UTC, lhalam approved these changes

2021-03-11 09:44 UTC, lhalam commented on user/models.py
> +class User(AbstractBaseUser):
rename to CustomUser

2021-03-11 09:44 UTC, lhalam commented on user/tests.py
> +# Create your tests here.
delete this file

2021-03-11 10:45 UTC, merged