Feature/#17
Lv-581-Python-project/todoProject pull request #46
Opened 2021-03-12 15:42 UTC by OstapOmelchuk

2021-03-13 13:24 UTC, daniiloleshchuk reviewed
fix identations and spaces please
and I don't understand, why manage.py is added to commit

2021-03-13 16:42 UTC, SLDem requested changes

2021-03-13 16:42 UTC, SLDem commented on task/models.py
> +        self.user_id = CustomUser.find_by_id(user_id)
change `find_by_id` to `get_by_id`

2021-03-15 11:32 UTC, SLDem approved these changes

2021-03-15 11:34 UTC, closed without merging